# Serverless config for PubCrawl

service: mypubcrawl
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-2:074584043282:*"

    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  pubs:
    handler: handler.pubs

    events:
      - http:
          path: pubs
          method: get

  pubcrawls:
    handler: handler.pubcrawls

    events:
      - http:
          path: pubcrawls
          method: any

  sendemail:
    handler: handler.sendemail

    events:
      - http:
          path: sendemail
          method: any
